/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:3.1.0")
    api("org.springframework.boot:spring-boot-starter-data-jpa:3.1.0")
    api("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0")
    api("org.postgresql:postgresql:42.6.0")
    api("org.flywaydb:flyway-core:9.16.3")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.1.0")
}

group = "com.bezdekova"
version = "0.0.1-SNAPSHOT"
description = "books"
java.sourceCompatibility = JavaVersion.VERSION_17

//publishing {
//    publications.create<MavenPublication>("maven") {
//        from(components["java"])
//    }
//}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
