version: '3.7'
services:
  postgres:
    image: postgres:13.4
    volumes:
      - postgres_data:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
volumes:
  postgres_data:
