spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/local
    username: local
    password: local
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
